apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: amirhossein21/sample-nginx:v0.1.4
    ports:
      - containerPort: 8080
    volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-dir
            - mountPath: /var/cache/nginx/
              name: nginx-empty
            - mountPath: /var/run/
              name: nginx-run
  volumes:
        - name: nginx-dir
          emptyDir: { }
        - name: nginx-empty
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }
