apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-dir
            - mountPath: /var/cache/nginx/client_temp
              name: nginx-empty
            - mountPath: /var/run/
              name: nginx-run
  volumes:
        - name: nginx-dir
          emptyDir: { }
        - name: nginx-empty
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }
