apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
        - name: sample-nginx
          image: amirhossein21/sample-nginx:v0.1.3
          ports:
            - containerPort: 80
              name: sample-nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-dir
            - mountPath: /var/cache/nginx/client_temp
              name: nginx-empty
            - mountPath: /var/run/
              name: nginx-run
      volumes:
        - name: nginx-dir
          emptyDir: { }
        - name: nginx-empty
          emptyDir: { }
        - name: nginx-run
          emptyDir: { }
