apiVersion: apps/v1
kind: Deployment

metadata:
  name: sample-nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-nginx
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
        - name: sample-nginx
          image: amirhossein21/sample-nginx:v0.1.0
          ports:
            - containerPort: 80
              name: sample-nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
